### ISSUE TITLE
Failing to install pygnmi on CentOS with 'ascii' codec can't decode error

### ISSUE THREAD

**Issue by dmulyalin** [akarneliuk/pygnmi#52]
Hi,

As stated in subject, failing to install pygnmi on Centos with Python 3.6.8 with this error:

```
[root@host /]# python3 -m pip install pygnmi --upgrade
Requirement already satisfied: pygnmi in /usr/local/lib/python3.6/site-packages (0.5.3)
Collecting pygnmi
  Using cached pygnmi-0.6.7.tar.gz (29 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vttklldz/pygnmi_6a28cc3abbfb4c57a7bb4ef96aa200a1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vttklldz/pygnmi_6a28cc3abbfb4c57a7bb4ef96aa200a1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-s5mrssho
       cwd: /tmp/pip-install-vttklldz/pygnmi_6a28cc3abbfb4c57a7bb4ef96aa200a1/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-vttklldz/pygnmi_6a28cc3abbfb4c57a7bb4ef96aa200a1/setup.py", line 4, in <module>
      long_description = fh.read()
    File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1864: ordinal not in range(128)
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7e/51/0985a330bd13318518f391edbf8797b7dbbf2003e3ff78161a197a02a295/pygnmi-0.6.7.tar.gz#sha256=b346c43ef1780badf420cb7f06827a6ce6b555fa3af0f21d286be551badb2868 (from https://pypi.org/simple/pygnmi/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Was able to fix the issue by specifying the encoding to use for opening readme file in setup.py:

```
[root@host pygnmi]# cat setup.py 
from distutils.core import setup

with open('README.rst', encoding="utf-8") as fh:
    long_description = fh.read()
```

after adding `encoding="utf-8"` can install with no issues:
```
[root@host pygnmi]# python3 -m pip install .
Processing /root/pygnmi
  Preparing metadata (setup.py) ... done
Requirement already satisfied: grpcio in /usr/local/lib64/python3.6/site-packages (from pygnmi==0.6.7) (1.43.0)
Requirement already satisfied: grpcio-tools in /usr/local/lib64/python3.6/site-packages (from pygnmi==0.6.7) (1.43.0)
Requirement already satisfied: kthread in /usr/local/lib/python3.6/site-packages (from pygnmi==0.6.7) (0.2.2)
Requirement already satisfied: cryptography in /usr/local/lib64/python3.6/site-packages (from pygnmi==0.6.7) (36.0.1)
Collecting dictdiffer
  Downloading dictdiffer-0.9.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.6/site-packages (from cryptography->pygnmi==0.6.7) (1.15.0)
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python3.6/site-packages (from grpcio->pygnmi==0.6.7) (1.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from grpcio-tools->pygnmi==0.6.7) (59.6.0)
Requirement already satisfied: protobuf<4.0dev,>=3.5.0.post1 in /usr/local/lib64/python3.6/site-packages (from grpcio-tools->pygnmi==0.6.7) (3.19.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.12->cryptography->pygnmi==0.6.7) (2.21)
Building wheels for collected packages: pygnmi
  Building wheel for pygnmi (setup.py) ... done
  Created wheel for pygnmi: filename=pygnmi-0.6.7-py3-none-any.whl size=32631 sha256=faa39de9c4938710810842707e4ca93d897f980fa8e6e99b85ce00ec76f2126b
  Stored in directory: /tmp/pip-ephem-wheel-cache-ixnhdp84/wheels/bc/83/38/7f21b3a28050665ce96fec2ff33c00c61381e6e1f71ce7df3b
Successfully built pygnmi
Installing collected packages: dictdiffer, pygnmi
  Attempting uninstall: pygnmi
    Found existing installation: pygnmi 0.5.3
    Uninstalling pygnmi-0.5.3:
      Successfully uninstalled pygnmi-0.5.3
Successfully installed dictdiffer-0.9.0 pygnmi-0.6.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@host pygnmi]#
```

**Comment by dmulyalin** [comment]
Not sure if there is a better way to fix this issue, might be OS related, i've tried standard things like upgrading pip and setuptools, but problem still stays, OS also seems to have latest packages installed as did `yum install update`

**Comment by akarneliuk** [comment]
Hey @dmulyalin ,

It took a bit, but now the issue shall be fixed in the latest release. Could you please check.

Best,
Anton

**Comment by dmulyalin** [comment]
Yes, looks good, can install it on CentOS now:
```
[root@192-168-064-133 /]# python3 -m pip install pygnmi
Collecting pygnmi
  Downloading pygnmi-0.6.8.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Collecting grpcio
  Downloading grpcio-1.43.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)
     |████████████████████████████████| 4.1 MB 4.0 MB/s            
Collecting grpcio-tools
  Downloading grpcio_tools-1.43.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 2.7 MB/s            
Collecting kthread
  Downloading kthread-0.2.2.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cryptography in /usr/local/lib64/python3.6/site-packages (from pygnmi) (36.0.1)
Collecting dictdiffer
  Downloading dictdiffer-0.9.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.6/site-packages (from cryptography->pygnmi) (1.14.5)
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python3.6/site-packages (from grpcio->pygnmi) (1.15.0)
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from grpcio-tools->pygnmi) (39.2.0)
Collecting protobuf<4.0dev,>=3.5.0.post1
  Downloading protobuf-3.19.4-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 5.8 MB/s            
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.12->cryptography->pygnmi) (2.20)
Using legacy 'setup.py install' for pygnmi, since package 'wheel' is not installed.
Using legacy 'setup.py install' for kthread, since package 'wheel' is not installed.
Installing collected packages: protobuf, grpcio, kthread, grpcio-tools, dictdiffer, pygnmi
    Running setup.py install for kthread ... done
    Running setup.py install for pygnmi ... done
Successfully installed dictdiffer-0.9.0 grpcio-1.43.0 grpcio-tools-1.43.0 kthread-0.2.2 protobuf-3.19.4 pygnmi-0.6.8
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@192-168-064-133 /]# hostnamectl
   Static hostname: localhost.localdomain
Transient hostname: 192-168-064-133.tpgi.com.au
         Icon name: computer-vm
           Chassis: vm
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1160.21.1.el7.x86_64
      Architecture: x86-64
[root@192-168-064-133 /]# 
```

thank you for fixing it.
