### ISSUE TITLE
sub `once` doesnt close the session

### ISSUE THREAD

**Issue by ksator** [akarneliuk/pygnmi#72]
Hello
```
arista@devbox:~$ pip freeze | grep pyg
pygnmi==0.7.4
arista@devbox:~$ 
``` 
would like to use pygnmi with the `sub` rpc with `once`.  

```
arista@devbox:~$ cat test7.py 
"""
pygnmi script
"""
from pygnmi.client import gNMIclient

TELEMETRY_REQUEST = {
                         'subscription': [
                             {
                                 'path': '/inventory/state/device/device-id'
                             }
                         ],
                         'mode': 'once',
                         'encoding': 'json'
                     }

with open("token.tok") as f:
    TOKEN = f.read().strip('\n')

if __name__ == "__main__":
     with gNMIclient(target=('192.168.0.5', '443'), token=TOKEN, skip_verify=True) as gconn:
         inventory = gconn.subscribe2(subscribe=TELEMETRY_REQUEST)
         for device in inventory:
                print(device)
```
It works  
but it doesnt close the session as you can see below ... (so I did CNTL + C to stop it)  
```
rista@devbox:~$ python test7.py 
ssl_target_name_override is applied, should be used for testing only!
{'update': {'update': [{'path': 'inventory/state/device[device-id=cvx01]/device-id', 'val': 'cvx01'}], 'timestamp': 1657867500000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=leaf3]/device-id', 'val': 'leaf3'}], 'timestamp': 1657867500000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=leaf4]/device-id', 'val': 'leaf4'}], 'timestamp': 1657867500000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=host1]/device-id', 'val': 'host1'}], 'timestamp': 1657867500000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=spine1]/device-id', 'val': 'spine1'}], 'timestamp': 1657867500000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=spine2]/device-id', 'val': 'spine2'}], 'timestamp': 1657867500000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=leaf1]/device-id', 'val': 'leaf1'}], 'timestamp': 1657867500000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=leaf2]/device-id', 'val': 'leaf2'}], 'timestamp': 1657867500000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=host2]/device-id', 'val': 'host2'}], 'timestamp': 1657867500000000000, 'prefix': ''}}
{'sync_response': True}









^CTraceback (most recent call last):
  File "/home/arista/test7.py", line 22, in <module>
    for device in inventory:
  File "/home/arista/.local/lib/python3.9/site-packages/pygnmi/client.py", line 990, in __next__
    return self.next()
  File "/home/arista/.local/lib/python3.9/site-packages/pygnmi/client.py", line 996, in next
    return self._next_update(timeout=None)
  File "/home/arista/.local/lib/python3.9/site-packages/pygnmi/client.py", line 1066, in _next_update
    return self._get_one_update(timeout=timeout)
  File "/home/arista/.local/lib/python3.9/site-packages/pygnmi/client.py", line 959, in _get_one_update
    return telemetryParser(self._updates.get(block=True, timeout=timeout))
  File "/usr/local/lib/python3.9/queue.py", line 171, in get
    self.not_empty.wait()
  File "/usr/local/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt

arista@devbox:~$ 
```
gnmic equivalent command (it is OK i.e it stops by itself i.e no need to CNTL + C)
```
arista@devbox:~$ gnmic -a 192.168.0.5:443 --mode=once subscribe --path /inventory/state/device/device-id --token=`cat token.tok` --skip-verify
```

fyi pygnmi using sub and `stream` instead of `once` is OK 
```
"""
pygnmi script
"""

from pygnmi.client import gNMIclient

TELEMETRY_REQUEST = {
                         'subscription': [
                             {
                                 'path': '/inventory/state/device/device-id',
                                 'mode': 'target_defined'
                             }
                         ],
                         'mode': 'stream',
                         'encoding': 'json'
                     }

with open("token.tok") as f:
    TOKEN = f.read().strip('\n')

if __name__ == "__main__":
    with gNMIclient(target=('192.168.0.5', '443'), token=TOKEN, skip_verify=True) as gconn:
        inventory = gconn.subscribe2(subscribe=TELEMETRY_REQUEST)
        for device in inventory:
            print(device)
```

**Comment by akarneliuk** [comment]
Hello @ksator ,

Thanks for your request. I've carefully reviewed. Whilst it is possible to stop the iterator for `ONCE` telemetry mode, it will truncate the last received message that is `{"sync_response": True}`. As `pygnmi` exists for almost two years, different people built different workflows using it, which may use that one.

By mindful that `pygnmi` is the python library first thing, though we have `pygnmicli` as well). That means that it gives you possibility to develop your application with its help matching your needs. Having said that, the easiest way to achieve what you want is to add 3 more lines to your script like as follows:
```
from pygnmi.client import gNMIclient

TELEMETRY_REQUEST = {
                         'subscription': [
                             {
                                 'path': '/inventory/state/device/device-id',
                                 'mode': 'target_defined'
                             }
                         ],
                         'mode': 'stream',
                         'encoding': 'json'
                     }

with open("token.tok") as f:
    TOKEN = f.read().strip('\n')

if __name__ == "__main__":
    with gNMIclient(target=('192.168.0.5', '443'), token=TOKEN, skip_verify=True) as gconn:
        inventory = gconn.subscribe2(subscribe=TELEMETRY_REQUEST)
        for device in inventory:
            print(device)

            if "mode" in TELEMETRY_REQUEST and TELEMETRY_REQUEST["mode"] == "once" and\
                    "sync_response" in item and item["sync_response"]:
                break
```
It will automatically terminate script once it will see the last message from the network device.

Please, let me know if there are any further questions, sir.

Best,
Anton

**Comment by akarneliuk** [comment]
Hello @ksator ,

as usual, thanks a lot for raising requests. We've amended the logic for the iterator class in case the telemetry mode is `once`. Now it will automatically terminate once it receives `{"sync_response": True}` message, whilst the message itself also pass to the results.

Best,
Anton

**Comment by ksator** [comment]
Hello @akarneliuk 
Thank you so much. 
It works using `0.7.5`. 
```
arista@devbox:~$ pip freeze | grep pyg
pygnmi==0.7.5
arista@devbox:~$ 
```
```
arista@devbox:~$ cat test.py 
"""
pygnmi script
"""
from pygnmi.client import gNMIclient

TELEMETRY_REQUEST = {
                         'subscription': [
                             {
                                 'path': '/inventory/state/device/device-id'
                             }
                         ],
                         'mode': 'once',
                         'encoding': 'json'
                     }

with open("token.tok") as f:
    TOKEN = f.read().strip('\n')

if __name__ == "__main__":
     with gNMIclient(target=('192.168.0.5', '443'), token=TOKEN, skip_verify=True) as gconn:
         inventory = gconn.subscribe2(subscribe=TELEMETRY_REQUEST)
         for device in inventory:
                print(device)
                
arista@devbox:~$ 
```

```
arista@devbox:~$ python test.py 
ssl_target_name_override is applied, should be used for testing only!
{'update': {'update': [{'path': 'inventory/state/device[device-id=leaf3]/device-id', 'val': 'leaf3'}], 'timestamp': 1658062800000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=spine2]/device-id', 'val': 'spine2'}], 'timestamp': 1658062800000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=cvx01]/device-id', 'val': 'cvx01'}], 'timestamp': 1658062800000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=leaf2]/device-id', 'val': 'leaf2'}], 'timestamp': 1658062800000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=spine1]/device-id', 'val': 'spine1'}], 'timestamp': 1658062800000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=host2]/device-id', 'val': 'host2'}], 'timestamp': 1658062800000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=leaf1]/device-id', 'val': 'leaf1'}], 'timestamp': 1658062800000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=leaf4]/device-id', 'val': 'leaf4'}], 'timestamp': 1658062800000000000, 'prefix': ''}}
{'update': {'update': [{'path': 'inventory/state/device[device-id=host1]/device-id', 'val': 'host1'}], 'timestamp': 1658062800000000000, 'prefix': ''}}
{'sync_response': True}
arista@devbox:~$ 
```
so I am closing this issue. 

Thanks!
